// Auto-generated by fetch_energy_data.py on 2026-04-10 (initial seed from hardcoded values)
// Source: EIA API v2, RGGI Inc.
// Do not edit manually — re-run the script or push to trigger GitHub Actions.

const DATA_META = {
  "generated": "2026-04-10T00:00:00",
  "latest_period": "2026-01",
  "latest_ma_rate": 31.16,
  "latest_us_rate": 17.45,
  "premium_pct": 79,
  "annual_overpayment": 987
};

const YEARS = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026];

// Electricity rates (¢/kWh, annual average)
const ELEC_MA = [14.6, 15.0, 14.8, 15.3, 16.1, 18.5, 18.2, 18.9, 20.0, 21.0, 22.0, 22.5, 25.4, 27.5, 29.0, 30.88, 31.16];
const ELEC_US = [11.5, 11.8, 11.9, 12.1, 12.5, 12.7, 12.6, 12.9, 13.0, 13.0, 13.2, 13.7, 15.5, 16.0, 16.9, 17.24, 17.45];

// State comparison rates (latest month, ¢/kWh)
const STATE_RATES = {
  "MA": 31.16,
  "US": 17.45,
  "RI": 30.14,
  "CT": 28.30,
  "NY": 28.37,
  "FL": 15.92,
  "TX": 15.69,
  "LA": 12.46
};

// Gasoline ($/gal, annual average)
const GAS_MA = [2.746, 3.528, 3.641, 3.537, 3.397, 2.364, 2.111, 2.401, 2.731, 2.579, 2.136, 2.927, 3.980, 3.447, 3.234, 2.970, null];
const GAS_US = [2.782, 3.521, 3.618, 3.505, 3.358, 2.429, 2.143, 2.415, 2.719, 2.604, 2.168, 3.008, 3.951, 3.519, 3.304, 3.097, null];

// Diesel ($/gal, annual average — NE PADD1A vs US)
const DSL_NE = [3.085, 3.978, 4.128, 4.079, 4.007, 2.892, 2.380, 2.690, 3.237, 3.131, 2.723, 3.228, 5.272, 4.514, 4.065, 3.963, null];
const DSL_US = [2.992, 3.840, 3.968, 3.922, 3.825, 2.707, 2.304, 2.650, 3.178, 3.056, 2.551, 3.287, 4.989, 4.214, 3.760, 3.660, null];

// Residential natural gas ($/therm, annual average)
const NG_MA = [1.32, 1.30, 1.25, 1.28, 1.35, 1.30, 1.20, 1.25, 1.35, 1.42, 1.38, 1.55, 2.10, 2.20, 2.51, 2.60, null];
const NG_US = [0.96, 0.93, 0.87, 0.93, 1.06, 0.98, 0.90, 0.95, 1.01, 1.02, 0.96, 1.08, 1.42, 1.21, 1.22, 1.25, null];

// RGGI MA auction proceeds ($M)
const RGGI_YEARS = [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];
const RGGI_PROCEEDS = [28.2, 50.9, 44.1, 27.2, 28.5, 74.0, 63.6, 74.3, 45.7, 34.4, 41.9, 46.3, 55.5, 97.5, 126.1, 128.5, 195.5, 200.4];
const RGGI_TOTAL = 1362.6;
