#!/usr/bin/env python3
"""
Rewrite the K constants block in the burden dashboard from one JSON file.

    data/burden-constants.json  ->  tax-burden-dashboard.html

Massachusetts and New Hampshire were once separate pages that hardcoded the same MA
figures, so a fiscal-year update could leave the site contradicting itself. They are now
one tabbed page sharing one engine, and every constant comes from the JSON below. Edit
the JSON, run this, never hand-edit the K object.

Three gates, all of which exit non-zero:

  1. PROVENANCE   every figure needs source + url + verified. verified:false blocks
                  publication. Use --allow-unverified to render a draft anyway.

  2. DERIVATION   meanHouseholdIncome and incomeShare are DERIVED from
                  aggregateHouseholdIncome / households, never hardcoded. Hardcoding
                  them is what broke the NH file: its households, mean and income share
                  implied a $17.50T national aggregate while MA's implied $14.91T.

  3. INVARIANCE   the federal layers must be identical across states for a given
                  household income. Layer 5 is
                      deficit * incShare_S / households_S * (income / mean_S)
                  which reduces to  deficit * income / nationalAggregate  -- state
                  invariant -- but only if the three constants agree. Gate 3 evaluates
                  it numerically for both states and fails if they diverge by >$1.

                  Before this gate existed the NH file showed $18,105 for MA and
                  $15,431 for NH on a line captioned "Identical basis", and that
                  spurious $2,674 discount was enough to make the headline compression
                  chart show the NH advantage RE-EXPANDING at the final layer --
                  visually refuting the dashboard's own central argument.

Usage:
    python update-burden-constants.py                    # verify + write
    python update-burden-constants.py --check            # verify only, write nothing
    python update-burden-constants.py --allow-unverified # write with placeholders
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONSTANTS = HERE / "data" / "burden-constants.json"
TARGETS = [HERE / "tax-burden-dashboard.html"]

BEGIN = "/* BURDEN-CONSTANTS:BEGIN — generated by update-burden-constants.py, do not hand-edit */"
END = "/* BURDEN-CONSTANTS:END */"

# Layer 5 must return this for a household at any income, in any state.
INVARIANCE_TEST_INCOMES = [50_000, 113_900, 250_000, 1_400_000]
INVARIANCE_TOLERANCE = 1.00  # dollars


# ---------------------------------------------------------------- helpers

def fail(msg):
    print(f"\n\033[91mFAIL\033[0m  {msg}\n", file=sys.stderr)
    sys.exit(1)


def walk_figures(node, path=""):
    """Yield (path, figure_dict) for every leaf that looks like a sourced figure."""
    if isinstance(node, dict):
        if "value" in node and ("source" in node or "verified" in node):
            yield path, node
            return
        for k, v in node.items():
            if k.startswith("_") or k == "release":
                continue
            yield from walk_figures(v, f"{path}.{k}" if path else k)


def val(node, *keys):
    """Pull .value from a nested sourced figure."""
    for k in keys:
        node = node[k]
    return node["value"]


# ---------------------------------------------------------------- gate 1

def gate_provenance(data, allow_unverified):
    missing, unverified = [], []
    for path, fig in walk_figures(data):
        if fig.get("source") in (None, "") or fig.get("url") in (None, ""):
            missing.append(path)
        if fig.get("verified") is False:
            unverified.append((path, (fig.get("note") or "").split(".")[0]))

    if missing:
        fail("figures with no source or url:\n    " + "\n    ".join(missing))

    if unverified:
        head = "figures still unverified:\n" + "\n".join(
            f"    {p:<52} {n}" for p, n in unverified
        )
        if not allow_unverified:
            fail(
                head
                + "\n\n  These BLOCK publication. Verify them, or pass --allow-unverified\n"
                  "  to render a draft. Do not ship a transparency dashboard on placeholders."
            )
        print(f"\033[93mWARN\033[0m  {len(unverified)} unverified figure(s) rendered anyway:")
        for p, n in unverified:
            print(f"        {p:<52} {n}")
    return unverified


# ---------------------------------------------------------------- gate 2

def derive(data):
    """Derive mean household income and the share denominators. Never hardcoded."""
    nat = data["national_acs"]
    nat_hh = val(nat, "households")
    nat_agg = val(nat, "aggregateHouseholdIncome")
    nat_pop = val(nat, "population")

    if nat_agg <= 0 or nat_hh <= 0 or nat_pop <= 0:
        fail("national ACS denominators must all be positive")

    derived = {}
    for code, st in data["states"].items():
        acs = st["acs"]
        hh = val(acs, "households")
        agg = val(acs, "aggregateHouseholdIncome")
        pop = val(acs, "population")

        if hh <= 0 or agg <= 0:
            fail(f"{code}: households and aggregate income must be positive")
        if acs.get("release") != nat.get("release"):
            fail(
                f"{code}: ACS release '{acs.get('release')}' != national "
                f"'{nat.get('release')}'. Shares derived across releases are not comparable."
            )

        derived[code] = {
            "households": hh,
            "aggHhIncome": agg,
            "meanHhIncome": agg / hh,       # DERIVED
            "incShare": agg / nat_agg,      # DERIVED
            "popShare": pop / nat_pop,      # DERIVED
        }
    derived["_national"] = {"aggHhIncome": nat_agg, "households": nat_hh, "population": nat_pop}
    return derived


# ---------------------------------------------------------------- gate 3

def gate_invariance(data, derived):
    """The federal layers must not know which side of the border you live on."""
    deficit = val(data["federal"], "deficit")
    corp = val(data["federal"], "corporateReceipts")
    codes = [c for c in derived if not c.startswith("_")]
    nat_agg = derived["_national"]["aggHhIncome"]

    problems = []
    for income in INVARIANCE_TEST_INCOMES:
        # Layer 5: deficit share. Layer 3: the FEDERAL corporate slice, evaluated the
        # way the dashboards actually compute it -- a labour component scaled by income
        # and a capital component scaled by the ownership factor. Both must be routed
        # through NATIONAL denominators, or the capital half silently means "relative to
        # my own state's average" and the row stops being identical across the border.
        nat_hh = derived["_national"]["households"]
        nat_mean = nat_agg / nat_hh
        l5 = {}
        l3 = {}
        for c in codes:
            d = derived[c]
            wr = income / d["meanHhIncome"]
            l5[c] = deficit * d["incShare"] / d["households"] * wr
            for lshare, capf in ((0.25, 0.30), (0.50, 1.00), (0.0, 2.5)):
                got = (corp / nat_hh) * (lshare * (income / nat_mean) + (1 - lshare) * capf)
                l3.setdefault(f"{c}", got)

        for label, got in (("Layer 5 federal borrowing", l5), ("Layer 3 federal corporate", l3)):
            spread = max(got.values()) - min(got.values())
            if spread > INVARIANCE_TOLERANCE:
                detail = ", ".join(f"{c}=${got[c]:,.0f}" for c in codes)
                problems.append(f"    ${income:>9,}  {label:<28} {detail}  spread ${spread:,.0f}")

        # closed form: it must equal deficit * income / national aggregate
        expect = deficit * income / nat_agg
        for c in codes:
            if abs(l5[c] - expect) > INVARIANCE_TOLERANCE:
                problems.append(
                    f"    ${income:>9,}  {c} Layer 5 = ${l5[c]:,.0f} but closed form "
                    f"deficit*income/nationalAggregate = ${expect:,.0f}"
                )

    if problems:
        fail(
            "federal layers are NOT state-invariant:\n"
            + "\n".join(problems)
            + "\n\n  A household with the same income owes the same share of federal borrowing\n"
              "  on either side of the border. If these diverge, the state ACS figures are\n"
              "  mutually inconsistent -- check households, aggregate income and release."
        )
    print(f"\033[92m  ok\033[0m  federal layers state-invariant across {len(codes)} states "
          f"at {len(INVARIANCE_TEST_INCOMES)} income levels")


# ---------------------------------------------------------------- gate 5

def gate_component_bound(data):
    """A modelled component gap must not exceed the observed whole-price gap.

    Layer 4 claims MA policy charges exceed NH's by some cents/kWh. EIA publishes the
    all-in residential price for both states. If the modelled policy-charge gap is
    larger than the total price gap, every OTHER component (generation, transmission,
    distribution) has to be dearer in NH by the difference. Not impossible, but it is a
    strong claim that should be made deliberately rather than fall out of a placeholder.
    """
    have = {c: st for c, st in data["states"].items()
            if "retailElectricCentsPerKwh" in st.get("utility", {})}
    if len(have) < 2:
        return
    codes = sorted(have)
    retail = {c: val(have[c], "utility", "retailElectricCentsPerKwh") for c in codes}
    policy = {c: val(have[c], "utility", "electricPolicyCentsPerKwh") for c in codes}
    retail_gap = max(retail.values()) - min(retail.values())
    policy_gap = max(policy.values()) - min(policy.values())
    # The EIA baseline is a STATEWIDE average across every utility, including cheap
    # municipal light plants. Tariff figures come from one investor-owned utility, whose
    # all-in rate runs well above that average. Comparing the two directly is apples to
    # oranges, so only flag a gap large enough to be implausible on any reading.
    if policy_gap > retail_gap * 2.5:
        print(f"\033[93m  !!\033[0m  Layer 4 policy gap {policy_gap:.2f}c/kWh EXCEEDS the observed "
              f"retail price gap {retail_gap:.2f}c/kWh ("
              + ", ".join(f"{c} {retail[c]:.2f}c" for c in codes) + ")."
              "\n        Implies the cheaper-policy state is dearer on generation, transmission"
              "\n        and distribution combined. Verify the tariffs before publishing Layer 4.")
    else:
        print(f"\033[92m  ok\033[0m  Layer 4 policy gap {policy_gap:.2f}c/kWh within the "
              f"{retail_gap:.2f}c/kWh retail price gap")


# ---------------------------------------------------------------- vintage

def classify(path, rules):
    for pattern, cls in rules:
        if pattern.lower() in path.lower():
            return cls
    return "statutory"


def vintage(data):
    """Per-class oldest verified date, so the page can date itself honestly.

    Drift and provenance are different failures. This addresses drift only: it says
    what the filed numbers said on a date. Unverified figures are excluded outright --
    stamping a placeholder with a date would imply a currency it does not have.
    """
    rules = data["_meta"]["volatility"]["rules"]
    buckets = {}
    for path, fig in walk_figures(data):
        if fig.get("verified") is False:
            continue
        cls = classify(path, rules)
        buckets.setdefault(cls, []).append(str(fig["verified"]))
    out = {c: {"oldest": min(v), "newest": max(v), "count": len(v)}
           for c, v in buckets.items()}
    print("\033[92m  ok\033[0m  vintage: " + ", ".join(
        f"{c} {d['count']} figs, oldest {d['oldest']}" for c, d in sorted(out.items())))
    return out


# ---------------------------------------------------------------- gate 4

def gate_pool_split(data):
    """Where a verified combined total exists, the modelled sub-pools must sum to it.

    NH DAS publishes Business Taxes as one line ($1,102.6M for FY2025); the model needs
    it split into BPT (profits, capital incidence) and BET (compensation base, labour
    incidence). The split is an assumption, but it must not silently drift away from the
    audited total it is dividing.
    """
    for code, st in data["states"].items():
        if "businessTaxesTotal" not in st:
            continue
        total = val(st, "businessTaxesTotal")
        parts = val(st, "corporateExcisePool") + val(st, "enterpriseTaxPool")
        if abs(parts - total) > 1:
            fail(
                f"{code}: corporateExcisePool + enterpriseTaxPool = ${parts:,.0f} but the\n"
                f"  audited businessTaxesTotal is ${total:,.0f} (off by ${parts-total:,.0f}).\n"
                "  The BPT/BET division is an assumption; the total it divides is not."
            )
        share = val(st, "enterpriseTaxPool") / total if total else 0
        print(f"\033[92m  ok\033[0m  {code}: business-tax pools sum to the audited "
              f"${total/1e6:,.1f}M total (BET share {share*100:.0f}%, assumed)")


# ---------------------------------------------------------------- emit

def js_num(n):
    if n is None:
        return "Infinity"
    if isinstance(n, float) and n.is_integer() and abs(n) < 1e15:
        n = int(n)
    return repr(n)


def state_block(code, st, d, indent="    "):
    def v(*keys):
        return val(st, *keys)

    ex = v("personalExemption")
    lines = [
        f"{code}:{{",
        f"  name:{json.dumps(st['name'])},",
        f"  incomeRate:{js_num(v('incomeRate'))}, surtax:{js_num(v('surtaxRate'))}, "
        f"surThr:{js_num(v('surtaxThreshold'))},",
        f"  exempt:{{single:{js_num(ex['single'])}, mfj:{js_num(ex['mfj'])}}},",
        f"  investRate:{js_num(v('investmentIncomeRate'))}, "
        f"stGainsRate:{js_num(v('shortTermGainsRate'))},",
        f"  salesRate:{js_num(v('salesRate'))}, mealsRate:{js_num(v('mealsRate'))},",
        f"  gasCents:{js_num(v('gasCentsPerGal'))},",
        f"  corpPool:{js_num(v('corporateExcisePool'))}, betPool:{js_num(v('enterpriseTaxPool'))},",
        f"  households:{js_num(d['households'])}, aggHhIncome:{js_num(d['aggHhIncome'])},",
        f"  meanHhIncome:{js_num(round(d['meanHhIncome']))},   // DERIVED aggregate/households",
        f"  incShare:{d['incShare']:.9f},   // DERIVED state aggregate / national aggregate",
        f"  popShare:{d['popShare']:.9f},",
        f"  elecCents:{js_num(v('utility', 'electricPolicyCentsPerKwh'))}, "
        f"gasPolicyCents:{js_num(v('utility', 'gasPolicyCentsPerTherm'))},",
        f"  retailElecCents:{js_num(v('utility', 'retailElectricCentsPerKwh'))},   // EIA all-in price, bounds the policy component",
        f"  unfunded:{js_num(v('unfundedAccrualPerHousehold'))},   // deliberately 0 — disclosed as a stock, not billed",
        f"  unfundedStock:{js_num(v('unfundedPensionOnlyStock') if 'unfundedPensionOnlyStock' in st else v('unfundedLiabilityStock'))},",]
    if "unfundedPensionOnlyStock" in st:
        lines.append(f"  unfundedStockAll:{js_num(v('unfundedLiabilityStock'))},   // incl. OPEB — NOT comparable to NH")
    lines += [
    ]
    if "effectivePropertyRatePct" in st:
        lines.append(f"  propRatePct:{js_num(v('effectivePropertyRatePct'))},")
    if st.get("avgSingleFamilyBill", {}).get("value") is not None:
        lines.append(f"  avgSfBill:{js_num(v('avgSingleFamilyBill'))}, "
                     f"avgSfValue:{js_num(v('avgSingleFamilyValue'))},")
        bill, value = v("avgSingleFamilyBill"), v("avgSingleFamilyValue")
        lines.append(f"  propRatePct:{round(bill / value * 100, 4)},   // DERIVED bill/value")
    lines.append("}")
    return ("\n" + indent).join(lines)


def build_block(data, derived, unverified, vin):
    fed = data["federal"]
    br = val(fed, "brackets")

    def brackets(key):
        return "[" + ",".join(f"[{js_num(c)},{r}]" for c, r in br[key]) + "]"

    sd = val(fed, "standardDeduction")
    am = val(fed, "addlMedThreshold")
    states = ",\n\n    ".join(
        state_block(c, data["states"][c], derived[c]) for c in data["states"]
    )
    stamp = data["_meta"]["updated"]
    warn = ""
    if unverified:
        warn = ("\n// DRAFT — " + str(len(unverified)) + " constant(s) still unverified: "
                + ", ".join(p for p, _ in unverified) + "\n")

    return f"""{BEGIN}
// Source of truth: data/burden-constants.json   ·   regenerate: python update-burden-constants.py
// Last generated {stamp}. meanHhIncome and incShare are DERIVED — see gate 2 and 3 in the script.{warn}
const K = {{
  stdDed:{{single:{js_num(sd['single'])}, mfj:{js_num(sd['mfj'])}}},
  brackets:{{
    single:{brackets('single')},
    mfj:{brackets('mfj')}
  }},
  ssWageBase:{js_num(val(fed,'ssWageBase'))}, ssRate:{js_num(val(fed,'ssRate'))}, medRate:{js_num(val(fed,'medRate'))},
  addlMedThr:{{single:{js_num(am['single'])}, mfj:{js_num(am['mfj'])}}}, addlMedRate:{js_num(val(fed,'addlMedRate'))},
  fedGasCents:{js_num(val(fed,'gasCentsPerGal'))},
  fedDeficit:{js_num(val(fed,'deficit'))},
  fedCorpReceipts:{js_num(val(fed,'corporateReceipts'))},
  nationalAggHhIncome:{js_num(derived['_national']['aggHhIncome'])},
  nationalHouseholds:{js_num(derived['_national']['households'])},
  nationalMeanHhIncome:{js_num(round(derived['_national']['aggHhIncome'] / derived['_national']['households']))},

  // Point-in-time stamp. Drift only -- unverified figures are excluded, because
  // dating a placeholder would imply a currency it does not have.
  vintage:{json.dumps(vin, sort_keys=True)},
  unverifiedCount:{len(unverified)},
  generated:{json.dumps(stamp)},

  {states}
}};
{END}"""


def write_targets(block, check_only):
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    for path in TARGETS:
        if not path.exists():
            fail(f"target missing: {path.name}")
        text = path.read_text(encoding="utf-8")
        if not pattern.search(text):
            fail(
                f"{path.name} has no BURDEN-CONSTANTS block.\n"
                f"  Wrap its K object in:\n    {BEGIN}\n    ...\n    {END}"
            )
        new = pattern.sub(lambda _: block, text)
        if new == text:
            print(f"  --  {path.name} already current")
        elif check_only:
            print(f"  !!  {path.name} would change")
        else:
            path.write_text(new, encoding="utf-8", newline="\n")
            print(f"\033[92m  ok\033[0m  wrote {path.name}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    ap.add_argument("--allow-unverified", action="store_true", help="render placeholders anyway")
    args = ap.parse_args()

    if not CONSTANTS.exists():
        fail(f"missing {CONSTANTS}")
    data = json.loads(CONSTANTS.read_text(encoding="utf-8"))

    print(f"\nburden constants  ·  {CONSTANTS.relative_to(HERE)}\n")
    # --check is the CI gate, so it must be STRICT. Only --allow-unverified downgrades
    # placeholders to warnings, and it says so on the tin.
    unverified = gate_provenance(data, args.allow_unverified)
    derived = derive(data)
    for code in data["states"]:
        d = derived[code]
        print(f"\033[92m  ok\033[0m  {code}: {d['households']:,} households, "
              f"mean ${d['meanHhIncome']:,.0f}, income share {d['incShare']*100:.4f}% (derived)")
    gate_invariance(data, derived)

    gate_pool_split(data)
    gate_component_bound(data)
    vin = vintage(data)
    write_targets(build_block(data, derived, unverified, vin), args.check)
    print()
    if unverified and not args.check:
        print(f"\033[93m  {len(unverified)} unverified constant(s) are live in the HTML. "
              f"Not publishable until resolved.\033[0m\n")


if __name__ == "__main__":
    main()
